services:
  lainos:
    build: .
    container_name: lainos
    privileged: true
    network_mode: host
    command: /usr/local/bin/init-wrapper.sh
    stop_signal: SIGRTMIN+3
    volumes:
      - ./.data/home:/home/lainos:Z
      - nix:/nix
    restart: unless-stopped

volumes:
  nix:
