services:
  lainos:
    build: .
    container_name: lainos
    privileged: true
    network_mode: host
    command: /usr/local/bin/init-wrapper.sh
    stop_signal: SIGRTMIN+3
    volumes:
      - ./.data/config:/home/lainos/config:Z
      - ./.data/workspace:/home/lainos/workspace:Z
      - ./.data/lain:/home/lainos/.config/lain:Z
      - ./.data/local:/home/lainos/.local:Z
      - nix:/nix
    restart: unless-stopped

volumes:
  nix:
